spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  shouldUseDns: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    log-delta-diff: false
    eureka-server-connect-timeout-seconds: 60
    eureka-service-url-poll-interval-seconds: 15
    prefer-same-zone-eureka: true
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: true
    expected-client-renewal-interval-seconds: 20
  instance:
    lease-expiration-duration-in-seconds: 70
